### ISSUE TITLE
OSError: [Errno 5] Input/output error (when shutting down notebook server with mstat)

### ISSUE THREAD

**Issue by pllim** [jhunkeler/mstat#3]
```
Jupyter Notebook 6.5.2 is running at: ...
Shutdown this notebook server (y/[n])? yException in thread Thread-2 (_confirm_exit):
Traceback (most recent call last):
  File "python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "notebook/notebookapp.py", line 1954, in _confirm_exit
    line = sys.stdin.readline()
OSError: [Errno 5] Input/output error
```

**Comment by jhunkeler** [comment]
Fixed by https://github.com/jhunkeler/mstat/commit/c15b87b9e8137e7e9fafa0e6c3962218d3dda81d

```
[I 16:27:31.256 NotebookApp] Jupyter Notebook 6.5.2 is running at: ...
^C
[I 16:27:48.140 NotebookApp] Interrupted...
[I 16:27:48.140 NotebookApp] Shutting down 0 kernels
[I 16:27:48.141 NotebookApp] Shutting down 0 terminals
pid 281199 returned 0
MSTAT file written: /whatever/its/too/late/now/281199.mstat
```
